name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install Mono
      run: |
        sudo apt-get update
        sudo apt-get install -y mono-complete

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Pack NuGet package
      run: nuget pack nuget/gerrkoff.CodingStandards.nuspec -OutputDirectory ./nupkg

    - name: Extract package version
      id: package_version
      run: |
        PACKAGE_FILE=$(ls ./nupkg/*.nupkg | head -n 1)
        VERSION=$(basename $PACKAGE_FILE | sed 's/gerrkoff.CodingStandards.\(.*\).nupkg/\1/')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Package version: $VERSION"

    - name: Publish to NuGet.org
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

    - name: Unlist package from search
      run: dotnet nuget delete gerrkoff.CodingStandards ${{ steps.package_version.outputs.version }} --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --non-interactive
